language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: b9Oc1ylw85uCfgyJwftjsrg4yBuIQ2dRQbcdVg78OFY3MMnoRCIrZ4h5/pYmvN+fVTFwgqLOqVEY6VWl+dWTv1TnloqEqAFWUMMm+H103WPbOJR9DLvaxNzSvuzmvmeCwrWhVRJuxTLUkXqTkBwZVsqKZkPepDXZM9sP8WpnyHa/W1bwhQ3WDQ64eHYl9m0m0VzQRKvLNu11jEnw7rgEBbGZYP6zCgaM/0zWK7bUrYUjBYx6zAbcYZi/0U2/pA018J7B7bIv+j3K1+wmHTeVxoig5GfuV8Z8HXm/FnVyrYoaiO9jl1exwN0LSlRo2fRPw7bFUPaQJ9Tex5p7Hj7+vIdFmFdgDLS/Z1T0fl/88umIC8kdKWon0HShnOKqzmG4LXpzqAZO7TXlgWI6HjPUKFeFOHGw3pBtsBDkLLtu+GcUwc5gF17zQa1I9gEO4DzjDEAA6sK7G0i0be4O2vxAEbfK/nto/DNrd08dX5PvbxYUXLGqHL9B+pT7aYNaOt/9DAbCaGivmYierUrFErE+kpTDYZ52gIkER2QgX4/BJJd1w1mFY7yGj57wzqXta9ObcHDrDbDsntsxC3JnZybR3z+9jKoAySX1gj+xjrHvfes7Pr2+mLBegtW60Grb0E5JhsLb4cUVv0NLnWg30dxHPX07qreKwwnAXhObeTtIOPs=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: gtw6GCC0TtK4I5/ycRlN0j4HOr8IXR2IIytjh93s1nDZi7S+h0EBxI1e1pahaGIsDTjLxuae20ZaA2gszMHh5NKIs1QnIOGepR613A9CKAv2fgZMO/6Ww1IwU8Apv2yjW0fh2wXWxMKm07NWoaDCaS+lgzS+r7OJtEu1fhNNaodgjIdTHwTgMmX8KAADhGzHVPUuXsBlo6P9k5AfeTmG+9ufLzIVu/9wf3uSUOsS9352D7zw/c+taRl62+tB2V0pwCuwskDCB1QzerVqcrQlwDMkY8EzWsVauVwzb4XPUrbCciFRE5VLoIj1RlDT6a7XSvw5DPMQpgfg+j1BsYa+PeYoh+TZUASeox9KCiuBpr/VJEaYNs564hDpGw2K2aYdUgBQcPaQ9AOmyMsGH6inovVLmXsGp4VDQeMiFmGVxr5B0F/RvDuRP4dOBJW9mX1hGXyqhWGUK53gsevOUMAsmujPPwfNJTJa9lzVh6rXpauTP9tOPml/WhxRULbNY270vBhJ6GT0uLgHVhZBy8zh9df4ZNL49XQlvovK/LnICj3p6uzSyiScGuIlxgd2sa7Wf97mTzC9mMRA+iwVCLPi5SJaucCJgEoFFDnMgLuPyky9ziVUkS7+RRhNGC7E+Rcrn/RAxZAGfLc7GOG6IuCHHE/yvIw98KpxYumiPQ2dNs0=
sudo: false
